name: gpp
channels:
  - conda-forge
  - defaults
dependencies:
  - beautifulsoup4=4.10
  - black=20
  - ipython=7.27
  - jedi=0.18
  - jupyter=1.0
  - jupyterlab=3.1
  - lxml=4.6
  - markdown2=2.4
  - matplotlib=3.4
  - nb_black=1.0
  - nb_conda=2.2
  - nbconvert==7.10.0
  - nltk=3.6
  - notebook=6.4.4
  - numpy=1.21
  - pandas=1.3
  - pillow=8.3
  - pip=21
  - pytest-notebook=0.6
  - python=3.9
  - pyyaml=6.0
  - requests=2.26
  - scikit-learn=1.0
  - scipy=1.7
  - seaborn=0.11
  - statsmodels=0.12
  - tabulate=0.8
  - tqdm=4
  - xlrd=2
  - geopandas
  - geodatasets
  - pip:
    - dataframe_image
    - gensim==3.8
    - keras==2.6
    - markdown
    - missingno
    - nbval
    - noisereduce
    - tensorflow-hub==0.12
    - tensorflow==2.6
    - tensorflow-estimator==2.6