name: gpp
channels:
  - conda-forge
  - defaults
dependencies:
  - anyio=3.7.1
  - appdirs=1.4.4
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - attrs=23.2.0
  - babel=2.14.0
  - backcall=0.2.0
  - beautifulsoup4=4.10.0
  - black=20.8b1
  - blas=1.0
  - bleach=6.1.0
  - bottleneck=1.3.7
  - branca=0.6.0
  - brotli=1.0.9
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2024.3.11
  - certifi=2024.6.2
  - cffi=1.16.0
  - cfitsio=3.470
  - charset-normalizer=2.0.12
  - click=8.1.7
  - click-plugins=1.1.1
  - cligj=0.7.2
  - colorama=0.4.6
  - comm=0.2.1
  - contourpy=1.2.0
  - curl=8.5.0
  - cycler=0.12.1
  - dataclasses=0.8
  - debugpy=1.8.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - exceptiongroup=1.2.0
  - expat=2.6.2
  - fiona=1.8.22
  - folium=0.14.0
  - fonttools=4.51.0
  - freetype=2.12.1
  - freexl=1.0.6
  - gdal=3.0.2
  - geodatasets=2023.12.0
  - geopandas=0.12.2
  - geopandas-base=0.12.2
  - geos=3.8.0
  - geotiff=1.6.0
  - gettext=0.21.1
  - gitdb=4.0.11
  - gitpython=3.1.42
  - glib=2.78.4
  - glib-tools=2.78.4
  - gst-plugins-base=1.22.9
  - gstreamer=1.22.9
  - hdf4=4.2.13
  - hdf5=1.10.6
  - icc_rt=2022.1.0
  - icu=58.2
  - idna=3.6
  - importlib-metadata=7.0.1
  - importlib_metadata=7.0.1
  - importlib_resources=6.1.2
  - iniconfig=2.0.0
  - intel-openmp=2023.1.0
  - ipykernel=6.29.3
  - ipython=7.27.0
  - ipython_genutils=0.2.0
  - ipywidgets=8.1.2
  - jedi=0.18.2
  - jinja2=3.1.3
  - joblib=1.3.2
  - jpeg=9e
  - json5=0.9.20
  - jsonschema=4.21.1
  - jsonschema-specifications=2023.12.1
  - jupyter=1.0.0
  - jupyter-server-mathjax=0.2.6
  - jupyter_client=8.6.0
  - jupyter_console=6.6.3
  - jupyter_core=5.7.1
  - jupyter_server=1.15.6
  - jupyterlab=3.1.19
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.16.6
  - jupyterlab_widgets=3.0.10
  - kealib=1.4.14
  - kiwisolver=1.4.5
  - krb5=1.20.1
  - lcms2=2.12
  - lerc=3.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcurl=8.5.0
  - libdeflate=1.10
  - libffi=3.4.2
  - libgdal=3.0.2
  - libglib=2.78.4
  - libhwloc=2.8.0
  - libiconv=1.17
  - liblapack=3.9.0
  - libnetcdf=4.6.1
  - libogg=1.3.4
  - libpng=1.6.43
  - libpq=12.15
  - libsodium=1.0.18
  - libspatialindex=1.9.3
  - libspatialite=4.3.0a
  - libsqlite=3.45.1
  - libssh2=1.10.0
  - libtiff=4.3.0
  - libvorbis=1.3.7
  - libxml2=2.9.14
  - libxslt=1.1.35
  - libzlib=1.2.13
  - lxml=4.6.5
  - lz4-c=1.9.4
  - m2w64-expat=2.1.1
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gettext=0.19.7
  - m2w64-gmp=6.1.0
  - m2w64-libiconv=1.14
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - m2w64-xz=5.2.2
  - mapclassify=2.5.0
  - markdown2=2.4.13
  - markupsafe=2.1.5
  - matplotlib=3.8.4
  - matplotlib-base=3.8.4
  - matplotlib-inline=0.1.6
  - mistune=2.0.4
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - msys2-conda-epoch=20160418
  - munch=2.5.0
  - mypy_extensions=1.0.0
  - nb_black=1.0.7
  - nb_conda=2.2.1
  - nb_conda_kernels=2.3.1
  - nbclassic=0.5.6
  - nbclient=0.5.13
  - nbconvert=7.10.0
  - nbdime=4.0.1
  - nbformat=5.9.2
  - nest-asyncio=1.6.0
  - networkx=3.1
  - nltk=3.6.7
  - notebook=6.4.4
  - notebook-shim=0.2.4
  - numexpr=2.8.7
  - numpy-base=1.22.3
  - olefile=0.47
  - openjpeg=2.5.0
  - openssl=1.1.1w
  - packaging=23.2
  - pandas=1.5.3
  - pandoc=2.19.2
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pathspec=0.12.1
  - patsy=0.5.6
  - pcre2=10.42
  - pickleshare=0.7.5
  - pillow=8.3.2
  - pip=21.3.1
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.2.0
  - pluggy=1.4.0
  - ply=3.11
  - postgresql=12.15
  - proj=6.2.1
  - prometheus_client=0.20.0
  - prompt-toolkit=3.0.42
  - prompt_toolkit=3.0.42
  - psutil=5.9.8
  - pthreads-win32=2.9.1
  - pycparser=2.21
  - pygments=2.17.2
  - pyparsing=3.0.9
  - pyproj=2.6.1.post1
  - pyqt=5.9.2
  - pyqt5-sip=12.12.2
  - pysocks=1.7.1
  - pytest=8.0.2
  - pytest-notebook=0.6.1
  - python=3.9.7
  - python-dateutil=2.9.0
  - python-fastjsonschema=2.19.1
  - python_abi=3.9
  - pytz=2024.1
  - pywin32=306
  - pywinpty=1.1.6
  - pyyaml=6.0.1
  - pyzmq=25.1.2
  - qt=5.9.7
  - qtconsole-base=5.5.1
  - qtpy=2.4.1
  - referencing=0.33.0
  - regex=2023.12.25
  - requests=2.26.0
  - rpds-py=0.18.0
  - rtree=1.0.1
  - scikit-learn=1.4.2
  - scipy=1.7.3
  - seaborn=0.11.2
  - seaborn-base=0.11.2
  - send2trash=1.8.2
  - setuptools=59.8.0
  - shapely=2.0.1
  - sip=4.19.13
  - smmap=5.0.0
  - sniffio=1.3.1
  - soupsieve=2.5
  - sqlite=3.36.0
  - statsmodels=0.12.2
  - tabulate=0.8.10
  - tbb=2021.8.0
  - terminado=0.18.0
  - testpath=0.6.0
  - threadpoolctl=3.3.0
  - tiledb=2.3.3
  - tinycss2=1.2.1
  - tk=8.6.13
  - toml=0.10.2
  - tomli=2.0.1
  - tornado=6.4
  - tqdm=4.66.2
  - traitlets=5.9.0
  - typed-ast=1.5.5
  - tzdata=2024a
  - ucrt=10.0.22621.0
  - unicodedata2=15.1.0
  - urllib3=1.26.18
  - vc=14.3
  - vc14_runtime=14.38.33130
  - vs2015_runtime=14.38.33130
  - wcwidth=0.2.13
  - webencodings=0.5.1
  - websocket-client=1.7.0
  - wheel=0.42.0
  - widgetsnbextension=4.0.10
  - win_inet_pton=1.1.0
  - winpty=0.4.3
  - xerces-c=3.2.4
  - xlrd=2.0.1
  - xyzservices=2022.9.0
  - xz=5.2.6
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.17.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - absl-py==0.15.0
      - aiohttp==3.9.3
      - aiosignal==1.3.1
      - astunparse==1.6.3
      - async-timeout==4.0.3
      - audioread==3.0.1
      - backoff==2.2.1
      - clang==5.0
      - coverage==7.4.3
      - cssutils==2.9.0
      - dataframe-image==0.2.3
      - flatbuffers==1.12
      - frozenlist==1.4.1
      - gast==0.4.0
      - gensim==3.8.0
      - google-pasta==0.2.0
      - grpcio==1.62.0
      - h5py==3.1.0
      - html2image==2.0.4.3
      - keras==2.6.0
      - keras-preprocessing==1.1.2
      - librosa==0.9.2
      - llvmlite==0.39.1
      - markdown==3.5.2
      - missingno==0.5.2
      - monotonic==1.6
      - multidict==6.0.5
      - nbval==0.11.0
      - noisereduce==3.0.0
      - numba==0.56.4
      - numpy==1.19.5
      - opt-einsum==3.3.0
      - ploomber-core==0.2.25
      - ploomber-extension==0.1.1
      - pooch==1.8.1
      - posthog==3.5.0
      - protobuf==4.25.3
      - resampy==0.4.2
      - six==1.15.0
      - sklearn-evaluation==0.12.1
      - smart-open==7.0.1
      - soundfile==0.12.1
      - tensorboard==2.16.2
      - tensorboard-data-server==0.7.2
      - tensorflow==2.6.0
      - tensorflow-estimator==2.6.0
      - tensorflow-hub==0.12.0
      - termcolor==1.1.0
      - typing-extensions==3.7.4.3
      - werkzeug==3.0.1
      - wrapt==1.12.1
      - yarl==1.9.4